name: ai-cfia workflows

on:
  push:
    branches: [ main ]

jobs:
  my_job:
    name: Checkout Repository
    uses: actions/checkout@v3
  workflow1:
    name: workflow-build-container
    uses: ai-cfia/github-workflows/.github/workflows/workflow-build-container.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit
  workflow2:
    name: workflow-build-push-container-azure.yml
    uses: ai-cfia/github-workflows/.github/workflows/workflow-build-push-container-azure.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit
  workflow3:
    name: workflow-build-push-container-github-registry.yml
    uses: ai-cfia/github-workflows/.github/workflows/workflow-build-push-container-github-registry.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit
  workflow4:
    name: workflow-deploy-azure.yml
    uses: ai-cfia/github-workflows/.github/workflows/workflow-deploy-azure.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit
  workflow5:
    name: workflow-deploy-gcp.yml
    uses: ai-cfia/github-workflows/.github/workflows/workflow-deploy-gcp.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit
  workflow6:  
    name: workflow-gh-pages-deployment
    uses: ai-cfia/github-workflows/.github/workflows/workflow-gh-pages-deployment.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit
  workflow7:  
    name: workflow-lint-test-python
    uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-python.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit
  workflow8:
    name: workflow-markdown-check
    uses: ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit
  workflow9:
    name: workflow-repo-standards-validation
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit
  workflow10:  
    name: workflow-terraform-check
    uses: ai-cfia/github-workflows/.github/workflows/workflow-terraform-check.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit
  workflow11:
    name: workflow-vercel-deployment
    uses: ai-cfia/github-workflows/.github/workflows/workflow-vercel-deployment.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit
  workflow12:
    name: workflow-yaml-check
    uses: ai-cfia/github-workflows/.github/workflows/workflow-yaml-check.yml@main
    with: # to pass inputs to called workflow
        input: value
    secrets: inherit